services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Use the provided Dockerfile for the app
    ports:
      - "3000:3000"           # Map container's port 3000 to host's port 3000
    volumes:
      - .:/usr/src/app        # Mount local project directory into the container (helpful for local development)
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development  # Set the environment to development (use "production" for production)
      - PORT=3000             # Define app port if driven by environment variables
    command: npm start        # Start the application using the `start` script from package.json
    stdin_open: true
    tty: true